### ISSUE TITLE
Support if & elseif & else & for tags

### ISSUE THREAD

**Issue by zjuwjf** [flutter-view/flutter-view#20]
flutter-view is an amazing work. 

If it could support "if elseif else for' tags, it will be much more powerful.

sample like below
```pug
hello(flutter-view :user)
    Container(width=100)
      Padding(paddingLeft=10 paddingRight=10)
        if user.name then
            Text(value='Hello ${user.name}')
        else
            Image(src='${user.icon}')
```

**Comment by blueneogeo** [comment]
Hi @zjuwjf, 

Thank you for your suggestion!  I will definitely consider it.

You can currently do this, that will give the same result:

```javascript
hello(flutter-view :user)
    Container(width=100)
      Padding(paddingLeft=10 paddingRight=10)
        Text(if='user.name != null' value='Hello ${user.name}')
        Image(if='user.name == null' src='${user.icon}')
```

Would this also solve your problem?

You can also combine this with a [**slot** tag](https://docs.flutter-view.io/guide/flow-control#slot), which only shows the first child. That means if you put an if on the first slot entry, then the second becomes the else. Combined with some [shortcut tags](https://docs.flutter-view.io/reference/css-properties#padding), this will have the same result as your example:

```javascript
hello(flutter-view :user)
    .greeting(width=100 padding-left=10 padding-right=10)
        slot
            .message(if='user.name != null') Hello ${user.name}
            Image(:src='user.icon')
```

Here the **slot** will show only the .message container only if the user.name is set. Otherwise it will only show the Image with the icon.

Does this also solve your request?

**Comment by zjuwjf** [comment]
Got it!  A little weird, but solve my request. 

Thank you!
