### ISSUE TITLE
Support for SFC

### ISSUE THREAD

**Issue by nachokb** [flutter-view/flutter-view#22]
I'd like to know your opinion on adding support for Single File Components, like vuejs does (a single file containing `<template/>`, `<script/>`, `<style/>` sections);

**Comment by blueneogeo** [comment]
Hi, that was actually the original intention and inspiration.

However problem is that inlining Dart means that you lose all the nice code completion from Dart in the editors. The loss of productivity did not seem to weigh up against the benefits. It also encouraged bad behavior (too much program logic code in the controller). So back then we decided to keep things separate and as simple as possible.

So not completely opposed to it, but when we tried, we did not like it as much in practice as we liked it in VueJS. Difference of course is that VueJS uses Javascript which is dynamic, and Dart is static, and that gives you all those nice compiler/editor benefits, partially lost in the SFC model.

**Comment by blueneogeo** [comment]
Hi Nachokb, to summarize the above, it does not work as nicely and is more error prone because there is no IDE support for it, and you lose a lot of the nice benefits of Dart coding. If we could have IDE support that parses Dart, Sass and Pug within the SFC, it would be great. If someone were willing to help extend the VSCode plugin to make that work, I'd be willing to put in the extra for full SFC support.

Does this answer your question?

**Comment by nachokb** [comment]
Perfectly, thanks!

**Comment by nachokb** [comment]
So I'd need to check how JavaScript is indeed well supported within a .vue file
