### ISSUE TITLE
CSS selectors does not seem to work as intended

### ISSUE THREAD

**Issue by mlp1802** [flutter-view/flutter-view#25]
Let's say I have a date class somewhere

```
.date
   color: gray

```
and use it like this in pug

`container.date 23-7-2001`

I would like to be able to change that color with another selector that effectively overrides the default date class

```
.overdue .date
  color: red
```

then use it like this in pug

```
.overdue
    container.date 23-7-2001
```

I would expect the date text to turn red, but it doesn't

Is there another way to do this or what? I saw nothing in the documentation of CSS selectors, then yet I can hardly imagine such an important feature is not supported

**Comment by blueneogeo** [comment]
The CSS selectors are processed using a standard HTML processor, so everything you said should just work. 

I did a small test to verify.

Here I am setting the colors like you did:

<img width="765" alt="Screen Shot 2020-06-11 at 14 24 38" src="https://user-images.githubusercontent.com/832382/84385187-6cda4a00-abef-11ea-8d7f-fdd0f37e0aaa.png">

Here is the result:

<img width="351" alt="Screen Shot 2020-06-11 at 14 24 55" src="https://user-images.githubusercontent.com/832382/84385201-7499ee80-abef-11ea-8466-2b8014940b9e.png">

What could be going wrong in your case, what could be that you are using styles for one pug file in another pug file. The .sass and .pug files are name-matched, eg: welcome.pug and welcome.sass. Also, I saw you use `gray`, it should be `grey`, perhaps that also has to do with it?

tip: a pug class without a tag, such as `.date` automatically gets converted to `container.date` by flutter-view. However `container.date` should work as well. Just looks nicer. See the pug in my example.

**Comment by mlp1802** [comment]
Thanks for the extremely quick response. And thanks for making this project, I'ts truly amazing btw.

I'm afraid I oversimplyfied my example for the sake of clarity. I also have your example working.

The real code goes as follow, and the problem is still there
sass code
```
.content
  font-size: 12
  color: blue

.overdue .content
  color: red



```
Pug code
```
article(flutter-view :title[String], :content[String], :max-height[double])
    column
        .title ${title}
        constrained-box(:constraints="BoxConstraints(maxHeight:maxHeight??150)")
            single-child-scroll-view
                .content ${content}

deadline(flutter-view :action[KrizoAction])
    div
        article(:title="'Deadline'" :content="'23-7-2001'")

action-details(flutter-view :model[Model], :dispatch[DispatchMsg], :action[KrizoAction])
    .page
        column
            inkwell
                row.row-space-between
                    .overdue
                        deadline(:action="action") //should be red, but is blue
```
As you can see, the deadline component calls the article component, which displays the date using the content class.  I'm trying to hit that .content class with the selecter .overdue .content.

**Comment by blueneogeo** [comment]
Ahh, I see the issue.

What is happening is that from flutter-view's perspective, it looks at your pug structure, and does not see .content inside .overdue. It simply statically processes your pug file structure, while you are expecting it to work against the resulting component tree.

In other words, flutter-view works on your code before it is run. It does not understand how your code will run, it simply generates code from the structure it is given. So it does not know that when your code is run, the `deadline` component calls the `article` component which contains your content.

Instead flutter-view simply sees your html/pug structure as-is, and processes it. So it does not see `.content` within `.overdue`. Instead, it sees literally the two trees in your files:

1. article/column/constrained-box/single-child-scroll-view/container.content
2. action-details/container.page/column/inkwell/row.row-space-between/.overdue/deadline

Since these are two separate paths without overlap, it makes sense that `.overdue/.content` does not map, so it is not applied.

To solve this, you need to move the .overdue to be in the same tree. I assume you want to be able to call article from multiple places and it not be overdue always. I would advice to add a parameter to article if it is overdue, and then use a switch inside article to show it overdue or not. Something like:

```pug
article(flutter-view :title[String], :content[String], :max-height[double], :overdue[bool])
    column
        .title ${title}
        constrained-box(:constraints="BoxConstraints(maxHeight:maxHeight??150)")
            single-child-scroll-view
                 slot
                     .content.overdue(if='overdue') ${content}
                     .content ${content}
```

And then calling it with the overdue property set of course. There are other solutions as well.

**Comment by mlp1802** [comment]
OK thanks I thought it was something like that. However in my solution "article" is used for a bunch of other stuff not related to dates or deadlines so it would be bad pratice in this case to put anything related to "overdue" into it. Wouldn't you agree that this is a missing feature, since this would work on a webpage? I could imagine other people trying to do similar things. 
I know there are workarounds but no one near as elegant as just setting your CSS selectors.

**Comment by blueneogeo** [comment]
I'm afraid this is a hard limit on how flutter-view works. Since it works before event your code compiles, it has no way on knowing how your widget tree will look after rendering.

However as a benefit, that it will never be outdated as Dart and Flutter change, and will not have any performance impact or require extra libraries. A dynamic CSS system would have to intervene deeply into how Flutter itself works.
