### ISSUE TITLE
Support else statements

### ISSUE THREAD

**Issue by pedro-gilmora** [flutter-view/flutter-view#36]
Simply as fallback content management

**Comment by blueneogeo** [comment]
Hi Pedro, since the if is inside of a tag, there is no place to put an else. 

However there is a good solution: use a [**slot**](https://docs.flutter-view.io/guide/flow-control#slot).

As an example:

```pug
slot
     .loggedin(if="user != null") Hello ${user.name}!
     .loggedout You are not logged in
```

A slot only shows a single entry. By adding an `if` on the first entry, the first entry will be rendered if the condition is true, and the second entry if the condition is false, effectively becoming an else.

A nice benefit is that you can have multiple ifs, effectively giving you a switch as well:

```pug
slot
     .loggedin(if="user != null") Hello ${user.name}!
     .blocked(if="user.isBlocked()") You are no longer allowed in
     .loggedout You are not logged in
```

See here for more information: https://docs.flutter-view.io/guide/flow-control#slot
